// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"gokit-demo/ent/country"
	"gokit-demo/ent/countrylocation"
	"gokit-demo/ent/predicate"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CountryLocationQuery is the builder for querying CountryLocation entities.
type CountryLocationQuery struct {
	config
	ctx                *QueryContext
	order              []countrylocation.OrderOption
	inters             []Interceptor
	predicates         []predicate.CountryLocation
	withCountry        *CountryQuery
	withParent         *CountryLocationQuery
	withChildLocations *CountryLocationQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CountryLocationQuery builder.
func (clq *CountryLocationQuery) Where(ps ...predicate.CountryLocation) *CountryLocationQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit the number of records to be returned by this query.
func (clq *CountryLocationQuery) Limit(limit int) *CountryLocationQuery {
	clq.ctx.Limit = &limit
	return clq
}

// Offset to start from.
func (clq *CountryLocationQuery) Offset(offset int) *CountryLocationQuery {
	clq.ctx.Offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *CountryLocationQuery) Unique(unique bool) *CountryLocationQuery {
	clq.ctx.Unique = &unique
	return clq
}

// Order specifies how the records should be ordered.
func (clq *CountryLocationQuery) Order(o ...countrylocation.OrderOption) *CountryLocationQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// QueryCountry chains the current query on the "country" edge.
func (clq *CountryLocationQuery) QueryCountry() *CountryQuery {
	query := (&CountryClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(countrylocation.Table, countrylocation.FieldID, selector),
			sqlgraph.To(country.Table, country.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, countrylocation.CountryTable, countrylocation.CountryColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (clq *CountryLocationQuery) QueryParent() *CountryLocationQuery {
	query := (&CountryLocationClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(countrylocation.Table, countrylocation.FieldID, selector),
			sqlgraph.To(countrylocation.Table, countrylocation.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, countrylocation.ParentTable, countrylocation.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildLocations chains the current query on the "child_locations" edge.
func (clq *CountryLocationQuery) QueryChildLocations() *CountryLocationQuery {
	query := (&CountryLocationClient{config: clq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := clq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(countrylocation.Table, countrylocation.FieldID, selector),
			sqlgraph.To(countrylocation.Table, countrylocation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, countrylocation.ChildLocationsTable, countrylocation.ChildLocationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(clq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CountryLocation entity from the query.
// Returns a *NotFoundError when no CountryLocation was found.
func (clq *CountryLocationQuery) First(ctx context.Context) (*CountryLocation, error) {
	nodes, err := clq.Limit(1).All(setContextOp(ctx, clq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{countrylocation.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *CountryLocationQuery) FirstX(ctx context.Context) *CountryLocation {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CountryLocation ID from the query.
// Returns a *NotFoundError when no CountryLocation ID was found.
func (clq *CountryLocationQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = clq.Limit(1).IDs(setContextOp(ctx, clq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{countrylocation.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *CountryLocationQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CountryLocation entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CountryLocation entity is found.
// Returns a *NotFoundError when no CountryLocation entities are found.
func (clq *CountryLocationQuery) Only(ctx context.Context) (*CountryLocation, error) {
	nodes, err := clq.Limit(2).All(setContextOp(ctx, clq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{countrylocation.Label}
	default:
		return nil, &NotSingularError{countrylocation.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *CountryLocationQuery) OnlyX(ctx context.Context) *CountryLocation {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CountryLocation ID in the query.
// Returns a *NotSingularError when more than one CountryLocation ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *CountryLocationQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = clq.Limit(2).IDs(setContextOp(ctx, clq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{countrylocation.Label}
	default:
		err = &NotSingularError{countrylocation.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *CountryLocationQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CountryLocations.
func (clq *CountryLocationQuery) All(ctx context.Context) ([]*CountryLocation, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryAll)
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CountryLocation, *CountryLocationQuery]()
	return withInterceptors[[]*CountryLocation](ctx, clq, qr, clq.inters)
}

// AllX is like All, but panics if an error occurs.
func (clq *CountryLocationQuery) AllX(ctx context.Context) []*CountryLocation {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CountryLocation IDs.
func (clq *CountryLocationQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if clq.ctx.Unique == nil && clq.path != nil {
		clq.Unique(true)
	}
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryIDs)
	if err = clq.Select(countrylocation.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *CountryLocationQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *CountryLocationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryCount)
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, clq, querierCount[*CountryLocationQuery](), clq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (clq *CountryLocationQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *CountryLocationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, clq.ctx, ent.OpQueryExist)
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *CountryLocationQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CountryLocationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *CountryLocationQuery) Clone() *CountryLocationQuery {
	if clq == nil {
		return nil
	}
	return &CountryLocationQuery{
		config:             clq.config,
		ctx:                clq.ctx.Clone(),
		order:              append([]countrylocation.OrderOption{}, clq.order...),
		inters:             append([]Interceptor{}, clq.inters...),
		predicates:         append([]predicate.CountryLocation{}, clq.predicates...),
		withCountry:        clq.withCountry.Clone(),
		withParent:         clq.withParent.Clone(),
		withChildLocations: clq.withChildLocations.Clone(),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// WithCountry tells the query-builder to eager-load the nodes that are connected to
// the "country" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CountryLocationQuery) WithCountry(opts ...func(*CountryQuery)) *CountryLocationQuery {
	query := (&CountryClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withCountry = query
	return clq
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CountryLocationQuery) WithParent(opts ...func(*CountryLocationQuery)) *CountryLocationQuery {
	query := (&CountryLocationClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withParent = query
	return clq
}

// WithChildLocations tells the query-builder to eager-load the nodes that are connected to
// the "child_locations" edge. The optional arguments are used to configure the query builder of the edge.
func (clq *CountryLocationQuery) WithChildLocations(opts ...func(*CountryLocationQuery)) *CountryLocationQuery {
	query := (&CountryLocationClient{config: clq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	clq.withChildLocations = query
	return clq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CountryID uint64 `json:"country_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CountryLocation.Query().
//		GroupBy(countrylocation.FieldCountryID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (clq *CountryLocationQuery) GroupBy(field string, fields ...string) *CountryLocationGroupBy {
	clq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CountryLocationGroupBy{build: clq}
	grbuild.flds = &clq.ctx.Fields
	grbuild.label = countrylocation.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CountryID uint64 `json:"country_id,omitempty"`
//	}
//
//	client.CountryLocation.Query().
//		Select(countrylocation.FieldCountryID).
//		Scan(ctx, &v)
func (clq *CountryLocationQuery) Select(fields ...string) *CountryLocationSelect {
	clq.ctx.Fields = append(clq.ctx.Fields, fields...)
	sbuild := &CountryLocationSelect{CountryLocationQuery: clq}
	sbuild.label = countrylocation.Label
	sbuild.flds, sbuild.scan = &clq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CountryLocationSelect configured with the given aggregations.
func (clq *CountryLocationQuery) Aggregate(fns ...AggregateFunc) *CountryLocationSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *CountryLocationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range clq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, clq); err != nil {
				return err
			}
		}
	}
	for _, f := range clq.ctx.Fields {
		if !countrylocation.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *CountryLocationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CountryLocation, error) {
	var (
		nodes       = []*CountryLocation{}
		_spec       = clq.querySpec()
		loadedTypes = [3]bool{
			clq.withCountry != nil,
			clq.withParent != nil,
			clq.withChildLocations != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CountryLocation).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CountryLocation{config: clq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := clq.withCountry; query != nil {
		if err := clq.loadCountry(ctx, query, nodes, nil,
			func(n *CountryLocation, e *Country) { n.Edges.Country = e }); err != nil {
			return nil, err
		}
	}
	if query := clq.withParent; query != nil {
		if err := clq.loadParent(ctx, query, nodes, nil,
			func(n *CountryLocation, e *CountryLocation) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := clq.withChildLocations; query != nil {
		if err := clq.loadChildLocations(ctx, query, nodes,
			func(n *CountryLocation) { n.Edges.ChildLocations = []*CountryLocation{} },
			func(n *CountryLocation, e *CountryLocation) {
				n.Edges.ChildLocations = append(n.Edges.ChildLocations, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (clq *CountryLocationQuery) loadCountry(ctx context.Context, query *CountryQuery, nodes []*CountryLocation, init func(*CountryLocation), assign func(*CountryLocation, *Country)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*CountryLocation)
	for i := range nodes {
		if nodes[i].CountryID == nil {
			continue
		}
		fk := *nodes[i].CountryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(country.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "country_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (clq *CountryLocationQuery) loadParent(ctx context.Context, query *CountryLocationQuery, nodes []*CountryLocation, init func(*CountryLocation), assign func(*CountryLocation, *CountryLocation)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*CountryLocation)
	for i := range nodes {
		if nodes[i].ParentID == nil {
			continue
		}
		fk := *nodes[i].ParentID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(countrylocation.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parent_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (clq *CountryLocationQuery) loadChildLocations(ctx context.Context, query *CountryLocationQuery, nodes []*CountryLocation, init func(*CountryLocation), assign func(*CountryLocation, *CountryLocation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*CountryLocation)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(countrylocation.FieldParentID)
	}
	query.Where(predicate.CountryLocation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(countrylocation.ChildLocationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentID
		if fk == nil {
			return fmt.Errorf(`foreign-key "parent_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parent_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (clq *CountryLocationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.ctx.Fields
	if len(clq.ctx.Fields) > 0 {
		_spec.Unique = clq.ctx.Unique != nil && *clq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *CountryLocationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(countrylocation.Table, countrylocation.Columns, sqlgraph.NewFieldSpec(countrylocation.FieldID, field.TypeUint64))
	_spec.From = clq.sql
	if unique := clq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if clq.path != nil {
		_spec.Unique = true
	}
	if fields := clq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, countrylocation.FieldID)
		for i := range fields {
			if fields[i] != countrylocation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if clq.withCountry != nil {
			_spec.Node.AddColumnOnce(countrylocation.FieldCountryID)
		}
		if clq.withParent != nil {
			_spec.Node.AddColumnOnce(countrylocation.FieldParentID)
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *CountryLocationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(countrylocation.Table)
	columns := clq.ctx.Fields
	if len(columns) == 0 {
		columns = countrylocation.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.ctx.Unique != nil && *clq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CountryLocationGroupBy is the group-by builder for CountryLocation entities.
type CountryLocationGroupBy struct {
	selector
	build *CountryLocationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *CountryLocationGroupBy) Aggregate(fns ...AggregateFunc) *CountryLocationGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the selector query and scans the result into the given value.
func (clgb *CountryLocationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, clgb.build.ctx, ent.OpQueryGroupBy)
	if err := clgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CountryLocationQuery, *CountryLocationGroupBy](ctx, clgb.build, clgb, clgb.build.inters, v)
}

func (clgb *CountryLocationGroupBy) sqlScan(ctx context.Context, root *CountryLocationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*clgb.flds)+len(clgb.fns))
		for _, f := range *clgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*clgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CountryLocationSelect is the builder for selecting fields of CountryLocation entities.
type CountryLocationSelect struct {
	*CountryLocationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *CountryLocationSelect) Aggregate(fns ...AggregateFunc) *CountryLocationSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *CountryLocationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cls.ctx, ent.OpQuerySelect)
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CountryLocationQuery, *CountryLocationSelect](ctx, cls.CountryLocationQuery, cls, cls.inters, v)
}

func (cls *CountryLocationSelect) sqlScan(ctx context.Context, root *CountryLocationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
