// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"gokit-demo/ent/bank"
	"gokit-demo/ent/country"
	"gokit-demo/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUsername sets the "username" field.
func (uc *UserCreate) SetUsername(s string) *UserCreate {
	uc.mutation.SetUsername(s)
	return uc
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (uc *UserCreate) SetNillableUsername(s *string) *UserCreate {
	if s != nil {
		uc.SetUsername(*s)
	}
	return uc
}

// SetName sets the "name" field.
func (uc *UserCreate) SetName(s string) *UserCreate {
	uc.mutation.SetName(s)
	return uc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (uc *UserCreate) SetNillableName(s *string) *UserCreate {
	if s != nil {
		uc.SetName(*s)
	}
	return uc
}

// SetEmail sets the "email" field.
func (uc *UserCreate) SetEmail(s string) *UserCreate {
	uc.mutation.SetEmail(s)
	return uc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uc *UserCreate) SetNillableEmail(s *string) *UserCreate {
	if s != nil {
		uc.SetEmail(*s)
	}
	return uc
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (uc *UserCreate) SetEmailVerifiedAt(t time.Time) *UserCreate {
	uc.mutation.SetEmailVerifiedAt(t)
	return uc
}

// SetNillableEmailVerifiedAt sets the "email_verified_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableEmailVerifiedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetEmailVerifiedAt(*t)
	}
	return uc
}

// SetPassword sets the "password" field.
func (uc *UserCreate) SetPassword(s string) *UserCreate {
	uc.mutation.SetPassword(s)
	return uc
}

// SetPassword2 sets the "password2" field.
func (uc *UserCreate) SetPassword2(s string) *UserCreate {
	uc.mutation.SetPassword2(s)
	return uc
}

// SetCountryID sets the "country_id" field.
func (uc *UserCreate) SetCountryID(u uint64) *UserCreate {
	uc.mutation.SetCountryID(u)
	return uc
}

// SetNillableCountryID sets the "country_id" field if the given value is not nil.
func (uc *UserCreate) SetNillableCountryID(u *uint64) *UserCreate {
	if u != nil {
		uc.SetCountryID(*u)
	}
	return uc
}

// SetContactCountryID sets the "contact_country_id" field.
func (uc *UserCreate) SetContactCountryID(u uint64) *UserCreate {
	uc.mutation.SetContactCountryID(u)
	return uc
}

// SetNillableContactCountryID sets the "contact_country_id" field if the given value is not nil.
func (uc *UserCreate) SetNillableContactCountryID(u *uint64) *UserCreate {
	if u != nil {
		uc.SetContactCountryID(*u)
	}
	return uc
}

// SetContactNumber sets the "contact_number" field.
func (uc *UserCreate) SetContactNumber(s string) *UserCreate {
	uc.mutation.SetContactNumber(s)
	return uc
}

// SetNillableContactNumber sets the "contact_number" field if the given value is not nil.
func (uc *UserCreate) SetNillableContactNumber(s *string) *UserCreate {
	if s != nil {
		uc.SetContactNumber(*s)
	}
	return uc
}

// SetFullContactNumber sets the "full_contact_number" field.
func (uc *UserCreate) SetFullContactNumber(s string) *UserCreate {
	uc.mutation.SetFullContactNumber(s)
	return uc
}

// SetNillableFullContactNumber sets the "full_contact_number" field if the given value is not nil.
func (uc *UserCreate) SetNillableFullContactNumber(s *string) *UserCreate {
	if s != nil {
		uc.SetFullContactNumber(*s)
	}
	return uc
}

// SetIntroducerUserID sets the "introducer_user_id" field.
func (uc *UserCreate) SetIntroducerUserID(u uint64) *UserCreate {
	uc.mutation.SetIntroducerUserID(u)
	return uc
}

// SetNillableIntroducerUserID sets the "introducer_user_id" field if the given value is not nil.
func (uc *UserCreate) SetNillableIntroducerUserID(u *uint64) *UserCreate {
	if u != nil {
		uc.SetIntroducerUserID(*u)
	}
	return uc
}

// SetLang sets the "lang" field.
func (uc *UserCreate) SetLang(s string) *UserCreate {
	uc.mutation.SetLang(s)
	return uc
}

// SetNillableLang sets the "lang" field if the given value is not nil.
func (uc *UserCreate) SetNillableLang(s *string) *UserCreate {
	if s != nil {
		uc.SetLang(*s)
	}
	return uc
}

// SetAvatar sets the "avatar" field.
func (uc *UserCreate) SetAvatar(s string) *UserCreate {
	uc.mutation.SetAvatar(s)
	return uc
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (uc *UserCreate) SetNillableAvatar(s *string) *UserCreate {
	if s != nil {
		uc.SetAvatar(*s)
	}
	return uc
}

// SetCredit1 sets the "credit_1" field.
func (uc *UserCreate) SetCredit1(f float64) *UserCreate {
	uc.mutation.SetCredit1(f)
	return uc
}

// SetNillableCredit1 sets the "credit_1" field if the given value is not nil.
func (uc *UserCreate) SetNillableCredit1(f *float64) *UserCreate {
	if f != nil {
		uc.SetCredit1(*f)
	}
	return uc
}

// SetCredit2 sets the "credit_2" field.
func (uc *UserCreate) SetCredit2(f float64) *UserCreate {
	uc.mutation.SetCredit2(f)
	return uc
}

// SetNillableCredit2 sets the "credit_2" field if the given value is not nil.
func (uc *UserCreate) SetNillableCredit2(f *float64) *UserCreate {
	if f != nil {
		uc.SetCredit2(*f)
	}
	return uc
}

// SetCredit3 sets the "credit_3" field.
func (uc *UserCreate) SetCredit3(f float64) *UserCreate {
	uc.mutation.SetCredit3(f)
	return uc
}

// SetNillableCredit3 sets the "credit_3" field if the given value is not nil.
func (uc *UserCreate) SetNillableCredit3(f *float64) *UserCreate {
	if f != nil {
		uc.SetCredit3(*f)
	}
	return uc
}

// SetCredit4 sets the "credit_4" field.
func (uc *UserCreate) SetCredit4(f float64) *UserCreate {
	uc.mutation.SetCredit4(f)
	return uc
}

// SetNillableCredit4 sets the "credit_4" field if the given value is not nil.
func (uc *UserCreate) SetNillableCredit4(f *float64) *UserCreate {
	if f != nil {
		uc.SetCredit4(*f)
	}
	return uc
}

// SetCredit5 sets the "credit_5" field.
func (uc *UserCreate) SetCredit5(f float64) *UserCreate {
	uc.mutation.SetCredit5(f)
	return uc
}

// SetNillableCredit5 sets the "credit_5" field if the given value is not nil.
func (uc *UserCreate) SetNillableCredit5(f *float64) *UserCreate {
	if f != nil {
		uc.SetCredit5(*f)
	}
	return uc
}

// SetBankID sets the "bank_id" field.
func (uc *UserCreate) SetBankID(u uint64) *UserCreate {
	uc.mutation.SetBankID(u)
	return uc
}

// SetNillableBankID sets the "bank_id" field if the given value is not nil.
func (uc *UserCreate) SetNillableBankID(u *uint64) *UserCreate {
	if u != nil {
		uc.SetBankID(*u)
	}
	return uc
}

// SetBankAccountName sets the "bank_account_name" field.
func (uc *UserCreate) SetBankAccountName(s string) *UserCreate {
	uc.mutation.SetBankAccountName(s)
	return uc
}

// SetNillableBankAccountName sets the "bank_account_name" field if the given value is not nil.
func (uc *UserCreate) SetNillableBankAccountName(s *string) *UserCreate {
	if s != nil {
		uc.SetBankAccountName(*s)
	}
	return uc
}

// SetBankAccountNumber sets the "bank_account_number" field.
func (uc *UserCreate) SetBankAccountNumber(s string) *UserCreate {
	uc.mutation.SetBankAccountNumber(s)
	return uc
}

// SetNillableBankAccountNumber sets the "bank_account_number" field if the given value is not nil.
func (uc *UserCreate) SetNillableBankAccountNumber(s *string) *UserCreate {
	if s != nil {
		uc.SetBankAccountNumber(*s)
	}
	return uc
}

// SetNationalID sets the "national_id" field.
func (uc *UserCreate) SetNationalID(s string) *UserCreate {
	uc.mutation.SetNationalID(s)
	return uc
}

// SetNillableNationalID sets the "national_id" field if the given value is not nil.
func (uc *UserCreate) SetNillableNationalID(s *string) *UserCreate {
	if s != nil {
		uc.SetNationalID(*s)
	}
	return uc
}

// SetFirstLogin sets the "first_login" field.
func (uc *UserCreate) SetFirstLogin(b bool) *UserCreate {
	uc.mutation.SetFirstLogin(b)
	return uc
}

// SetNillableFirstLogin sets the "first_login" field if the given value is not nil.
func (uc *UserCreate) SetNillableFirstLogin(b *bool) *UserCreate {
	if b != nil {
		uc.SetFirstLogin(*b)
	}
	return uc
}

// SetBanUntil sets the "ban_until" field.
func (uc *UserCreate) SetBanUntil(t time.Time) *UserCreate {
	uc.mutation.SetBanUntil(t)
	return uc
}

// SetNillableBanUntil sets the "ban_until" field if the given value is not nil.
func (uc *UserCreate) SetNillableBanUntil(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetBanUntil(*t)
	}
	return uc
}

// SetNewLoginAt sets the "new_login_at" field.
func (uc *UserCreate) SetNewLoginAt(t time.Time) *UserCreate {
	uc.mutation.SetNewLoginAt(t)
	return uc
}

// SetNillableNewLoginAt sets the "new_login_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableNewLoginAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetNewLoginAt(*t)
	}
	return uc
}

// SetLastLoginAt sets the "last_login_at" field.
func (uc *UserCreate) SetLastLoginAt(t time.Time) *UserCreate {
	uc.mutation.SetLastLoginAt(t)
	return uc
}

// SetNillableLastLoginAt sets the "last_login_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableLastLoginAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetLastLoginAt(*t)
	}
	return uc
}

// SetUnilevel sets the "unilevel" field.
func (uc *UserCreate) SetUnilevel(u uint64) *UserCreate {
	uc.mutation.SetUnilevel(u)
	return uc
}

// SetNillableUnilevel sets the "unilevel" field if the given value is not nil.
func (uc *UserCreate) SetNillableUnilevel(u *uint64) *UserCreate {
	if u != nil {
		uc.SetUnilevel(*u)
	}
	return uc
}

// SetCreatedAt sets the "created_at" field.
func (uc *UserCreate) SetCreatedAt(t time.Time) *UserCreate {
	uc.mutation.SetCreatedAt(t)
	return uc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableCreatedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetCreatedAt(*t)
	}
	return uc
}

// SetUpdatedAt sets the "updated_at" field.
func (uc *UserCreate) SetUpdatedAt(t time.Time) *UserCreate {
	uc.mutation.SetUpdatedAt(t)
	return uc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableUpdatedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetUpdatedAt(*t)
	}
	return uc
}

// SetDeletedAt sets the "deleted_at" field.
func (uc *UserCreate) SetDeletedAt(t time.Time) *UserCreate {
	uc.mutation.SetDeletedAt(t)
	return uc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableDeletedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetDeletedAt(*t)
	}
	return uc
}

// SetPassword3 sets the "password3" field.
func (uc *UserCreate) SetPassword3(s string) *UserCreate {
	uc.mutation.SetPassword3(s)
	return uc
}

// SetNillablePassword3 sets the "password3" field if the given value is not nil.
func (uc *UserCreate) SetNillablePassword3(s *string) *UserCreate {
	if s != nil {
		uc.SetPassword3(*s)
	}
	return uc
}

// SetID sets the "id" field.
func (uc *UserCreate) SetID(u uint64) *UserCreate {
	uc.mutation.SetID(u)
	return uc
}

// SetCountry sets the "country" edge to the Country entity.
func (uc *UserCreate) SetCountry(c *Country) *UserCreate {
	return uc.SetCountryID(c.ID)
}

// SetContactCountry sets the "contact_country" edge to the Country entity.
func (uc *UserCreate) SetContactCountry(c *Country) *UserCreate {
	return uc.SetContactCountryID(c.ID)
}

// SetIntroducerID sets the "introducer" edge to the User entity by ID.
func (uc *UserCreate) SetIntroducerID(id uint64) *UserCreate {
	uc.mutation.SetIntroducerID(id)
	return uc
}

// SetNillableIntroducerID sets the "introducer" edge to the User entity by ID if the given value is not nil.
func (uc *UserCreate) SetNillableIntroducerID(id *uint64) *UserCreate {
	if id != nil {
		uc = uc.SetIntroducerID(*id)
	}
	return uc
}

// SetIntroducer sets the "introducer" edge to the User entity.
func (uc *UserCreate) SetIntroducer(u *User) *UserCreate {
	return uc.SetIntroducerID(u.ID)
}

// SetBank sets the "bank" edge to the Bank entity.
func (uc *UserCreate) SetBank(b *Bank) *UserCreate {
	return uc.SetBankID(b.ID)
}

// AddIntroducedUserIDs adds the "introduced_users" edge to the User entity by IDs.
func (uc *UserCreate) AddIntroducedUserIDs(ids ...uint64) *UserCreate {
	uc.mutation.AddIntroducedUserIDs(ids...)
	return uc
}

// AddIntroducedUsers adds the "introduced_users" edges to the User entity.
func (uc *UserCreate) AddIntroducedUsers(u ...*User) *UserCreate {
	ids := make([]uint64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return uc.AddIntroducedUserIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	uc.defaults()
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UserCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UserCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *UserCreate) defaults() {
	if _, ok := uc.mutation.Lang(); !ok {
		v := user.DefaultLang
		uc.mutation.SetLang(v)
	}
	if _, ok := uc.mutation.Credit1(); !ok {
		v := user.DefaultCredit1
		uc.mutation.SetCredit1(v)
	}
	if _, ok := uc.mutation.Credit2(); !ok {
		v := user.DefaultCredit2
		uc.mutation.SetCredit2(v)
	}
	if _, ok := uc.mutation.Credit3(); !ok {
		v := user.DefaultCredit3
		uc.mutation.SetCredit3(v)
	}
	if _, ok := uc.mutation.Credit4(); !ok {
		v := user.DefaultCredit4
		uc.mutation.SetCredit4(v)
	}
	if _, ok := uc.mutation.Credit5(); !ok {
		v := user.DefaultCredit5
		uc.mutation.SetCredit5(v)
	}
	if _, ok := uc.mutation.FirstLogin(); !ok {
		v := user.DefaultFirstLogin
		uc.mutation.SetFirstLogin(v)
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		uc.mutation.SetCreatedAt(v)
	}
	if _, ok := uc.mutation.UpdatedAt(); !ok {
		v := user.DefaultUpdatedAt()
		uc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *UserCreate) check() error {
	if _, ok := uc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "User.password"`)}
	}
	if v, ok := uc.mutation.Password(); ok {
		if err := user.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "User.password": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Password2(); !ok {
		return &ValidationError{Name: "password2", err: errors.New(`ent: missing required field "User.password2"`)}
	}
	if v, ok := uc.mutation.Password2(); ok {
		if err := user.Password2Validator(v); err != nil {
			return &ValidationError{Name: "password2", err: fmt.Errorf(`ent: validator failed for field "User.password2": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Lang(); !ok {
		return &ValidationError{Name: "lang", err: errors.New(`ent: missing required field "User.lang"`)}
	}
	if _, ok := uc.mutation.Credit1(); !ok {
		return &ValidationError{Name: "credit_1", err: errors.New(`ent: missing required field "User.credit_1"`)}
	}
	if _, ok := uc.mutation.Credit2(); !ok {
		return &ValidationError{Name: "credit_2", err: errors.New(`ent: missing required field "User.credit_2"`)}
	}
	if _, ok := uc.mutation.Credit3(); !ok {
		return &ValidationError{Name: "credit_3", err: errors.New(`ent: missing required field "User.credit_3"`)}
	}
	if _, ok := uc.mutation.Credit4(); !ok {
		return &ValidationError{Name: "credit_4", err: errors.New(`ent: missing required field "User.credit_4"`)}
	}
	if _, ok := uc.mutation.Credit5(); !ok {
		return &ValidationError{Name: "credit_5", err: errors.New(`ent: missing required field "User.credit_5"`)}
	}
	if _, ok := uc.mutation.FirstLogin(); !ok {
		return &ValidationError{Name: "first_login", err: errors.New(`ent: missing required field "User.first_login"`)}
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "User.created_at"`)}
	}
	if _, ok := uc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "User.updated_at"`)}
	}
	return nil
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64))
	)
	_spec.OnConflict = uc.conflict
	if id, ok := uc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uc.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := uc.mutation.Name(); ok {
		_spec.SetField(user.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := uc.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := uc.mutation.EmailVerifiedAt(); ok {
		_spec.SetField(user.FieldEmailVerifiedAt, field.TypeTime, value)
		_node.EmailVerifiedAt = &value
	}
	if value, ok := uc.mutation.Password(); ok {
		_spec.SetField(user.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := uc.mutation.Password2(); ok {
		_spec.SetField(user.FieldPassword2, field.TypeString, value)
		_node.Password2 = value
	}
	if value, ok := uc.mutation.ContactNumber(); ok {
		_spec.SetField(user.FieldContactNumber, field.TypeString, value)
		_node.ContactNumber = &value
	}
	if value, ok := uc.mutation.FullContactNumber(); ok {
		_spec.SetField(user.FieldFullContactNumber, field.TypeString, value)
		_node.FullContactNumber = &value
	}
	if value, ok := uc.mutation.Lang(); ok {
		_spec.SetField(user.FieldLang, field.TypeString, value)
		_node.Lang = value
	}
	if value, ok := uc.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
		_node.Avatar = &value
	}
	if value, ok := uc.mutation.Credit1(); ok {
		_spec.SetField(user.FieldCredit1, field.TypeFloat64, value)
		_node.Credit1 = value
	}
	if value, ok := uc.mutation.Credit2(); ok {
		_spec.SetField(user.FieldCredit2, field.TypeFloat64, value)
		_node.Credit2 = value
	}
	if value, ok := uc.mutation.Credit3(); ok {
		_spec.SetField(user.FieldCredit3, field.TypeFloat64, value)
		_node.Credit3 = value
	}
	if value, ok := uc.mutation.Credit4(); ok {
		_spec.SetField(user.FieldCredit4, field.TypeFloat64, value)
		_node.Credit4 = value
	}
	if value, ok := uc.mutation.Credit5(); ok {
		_spec.SetField(user.FieldCredit5, field.TypeFloat64, value)
		_node.Credit5 = value
	}
	if value, ok := uc.mutation.BankAccountName(); ok {
		_spec.SetField(user.FieldBankAccountName, field.TypeString, value)
		_node.BankAccountName = &value
	}
	if value, ok := uc.mutation.BankAccountNumber(); ok {
		_spec.SetField(user.FieldBankAccountNumber, field.TypeString, value)
		_node.BankAccountNumber = &value
	}
	if value, ok := uc.mutation.NationalID(); ok {
		_spec.SetField(user.FieldNationalID, field.TypeString, value)
		_node.NationalID = &value
	}
	if value, ok := uc.mutation.FirstLogin(); ok {
		_spec.SetField(user.FieldFirstLogin, field.TypeBool, value)
		_node.FirstLogin = value
	}
	if value, ok := uc.mutation.BanUntil(); ok {
		_spec.SetField(user.FieldBanUntil, field.TypeTime, value)
		_node.BanUntil = &value
	}
	if value, ok := uc.mutation.NewLoginAt(); ok {
		_spec.SetField(user.FieldNewLoginAt, field.TypeTime, value)
		_node.NewLoginAt = &value
	}
	if value, ok := uc.mutation.LastLoginAt(); ok {
		_spec.SetField(user.FieldLastLoginAt, field.TypeTime, value)
		_node.LastLoginAt = &value
	}
	if value, ok := uc.mutation.Unilevel(); ok {
		_spec.SetField(user.FieldUnilevel, field.TypeUint64, value)
		_node.Unilevel = &value
	}
	if value, ok := uc.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := uc.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := uc.mutation.DeletedAt(); ok {
		_spec.SetField(user.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := uc.mutation.Password3(); ok {
		_spec.SetField(user.FieldPassword3, field.TypeString, value)
		_node.Password3 = value
	}
	if nodes := uc.mutation.CountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.CountryTable,
			Columns: []string{user.CountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CountryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ContactCountryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.ContactCountryTable,
			Columns: []string{user.ContactCountryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(country.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ContactCountryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.IntroducerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.IntroducerTable,
			Columns: []string{user.IntroducerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.IntroducerUserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.BankIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.BankTable,
			Columns: []string{user.BankColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(bank.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BankID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.IntroducedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.IntroducedUsersTable,
			Columns: []string{user.IntroducedUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.Create().
//		SetUsername(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (uc *UserCreate) OnConflict(opts ...sql.ConflictOption) *UserUpsertOne {
	uc.conflict = opts
	return &UserUpsertOne{
		create: uc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (uc *UserCreate) OnConflictColumns(columns ...string) *UserUpsertOne {
	uc.conflict = append(uc.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertOne{
		create: uc,
	}
}

type (
	// UserUpsertOne is the builder for "upsert"-ing
	//  one User node.
	UserUpsertOne struct {
		create *UserCreate
	}

	// UserUpsert is the "OnConflict" setter.
	UserUpsert struct {
		*sql.UpdateSet
	}
)

// SetUsername sets the "username" field.
func (u *UserUpsert) SetUsername(v string) *UserUpsert {
	u.Set(user.FieldUsername, v)
	return u
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsert) UpdateUsername() *UserUpsert {
	u.SetExcluded(user.FieldUsername)
	return u
}

// ClearUsername clears the value of the "username" field.
func (u *UserUpsert) ClearUsername() *UserUpsert {
	u.SetNull(user.FieldUsername)
	return u
}

// SetName sets the "name" field.
func (u *UserUpsert) SetName(v string) *UserUpsert {
	u.Set(user.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsert) UpdateName() *UserUpsert {
	u.SetExcluded(user.FieldName)
	return u
}

// ClearName clears the value of the "name" field.
func (u *UserUpsert) ClearName() *UserUpsert {
	u.SetNull(user.FieldName)
	return u
}

// SetEmail sets the "email" field.
func (u *UserUpsert) SetEmail(v string) *UserUpsert {
	u.Set(user.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserUpsert) UpdateEmail() *UserUpsert {
	u.SetExcluded(user.FieldEmail)
	return u
}

// ClearEmail clears the value of the "email" field.
func (u *UserUpsert) ClearEmail() *UserUpsert {
	u.SetNull(user.FieldEmail)
	return u
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (u *UserUpsert) SetEmailVerifiedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldEmailVerifiedAt, v)
	return u
}

// UpdateEmailVerifiedAt sets the "email_verified_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateEmailVerifiedAt() *UserUpsert {
	u.SetExcluded(user.FieldEmailVerifiedAt)
	return u
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (u *UserUpsert) ClearEmailVerifiedAt() *UserUpsert {
	u.SetNull(user.FieldEmailVerifiedAt)
	return u
}

// SetPassword sets the "password" field.
func (u *UserUpsert) SetPassword(v string) *UserUpsert {
	u.Set(user.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *UserUpsert) UpdatePassword() *UserUpsert {
	u.SetExcluded(user.FieldPassword)
	return u
}

// SetPassword2 sets the "password2" field.
func (u *UserUpsert) SetPassword2(v string) *UserUpsert {
	u.Set(user.FieldPassword2, v)
	return u
}

// UpdatePassword2 sets the "password2" field to the value that was provided on create.
func (u *UserUpsert) UpdatePassword2() *UserUpsert {
	u.SetExcluded(user.FieldPassword2)
	return u
}

// SetCountryID sets the "country_id" field.
func (u *UserUpsert) SetCountryID(v uint64) *UserUpsert {
	u.Set(user.FieldCountryID, v)
	return u
}

// UpdateCountryID sets the "country_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateCountryID() *UserUpsert {
	u.SetExcluded(user.FieldCountryID)
	return u
}

// ClearCountryID clears the value of the "country_id" field.
func (u *UserUpsert) ClearCountryID() *UserUpsert {
	u.SetNull(user.FieldCountryID)
	return u
}

// SetContactCountryID sets the "contact_country_id" field.
func (u *UserUpsert) SetContactCountryID(v uint64) *UserUpsert {
	u.Set(user.FieldContactCountryID, v)
	return u
}

// UpdateContactCountryID sets the "contact_country_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateContactCountryID() *UserUpsert {
	u.SetExcluded(user.FieldContactCountryID)
	return u
}

// ClearContactCountryID clears the value of the "contact_country_id" field.
func (u *UserUpsert) ClearContactCountryID() *UserUpsert {
	u.SetNull(user.FieldContactCountryID)
	return u
}

// SetContactNumber sets the "contact_number" field.
func (u *UserUpsert) SetContactNumber(v string) *UserUpsert {
	u.Set(user.FieldContactNumber, v)
	return u
}

// UpdateContactNumber sets the "contact_number" field to the value that was provided on create.
func (u *UserUpsert) UpdateContactNumber() *UserUpsert {
	u.SetExcluded(user.FieldContactNumber)
	return u
}

// ClearContactNumber clears the value of the "contact_number" field.
func (u *UserUpsert) ClearContactNumber() *UserUpsert {
	u.SetNull(user.FieldContactNumber)
	return u
}

// SetFullContactNumber sets the "full_contact_number" field.
func (u *UserUpsert) SetFullContactNumber(v string) *UserUpsert {
	u.Set(user.FieldFullContactNumber, v)
	return u
}

// UpdateFullContactNumber sets the "full_contact_number" field to the value that was provided on create.
func (u *UserUpsert) UpdateFullContactNumber() *UserUpsert {
	u.SetExcluded(user.FieldFullContactNumber)
	return u
}

// ClearFullContactNumber clears the value of the "full_contact_number" field.
func (u *UserUpsert) ClearFullContactNumber() *UserUpsert {
	u.SetNull(user.FieldFullContactNumber)
	return u
}

// SetIntroducerUserID sets the "introducer_user_id" field.
func (u *UserUpsert) SetIntroducerUserID(v uint64) *UserUpsert {
	u.Set(user.FieldIntroducerUserID, v)
	return u
}

// UpdateIntroducerUserID sets the "introducer_user_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateIntroducerUserID() *UserUpsert {
	u.SetExcluded(user.FieldIntroducerUserID)
	return u
}

// ClearIntroducerUserID clears the value of the "introducer_user_id" field.
func (u *UserUpsert) ClearIntroducerUserID() *UserUpsert {
	u.SetNull(user.FieldIntroducerUserID)
	return u
}

// SetLang sets the "lang" field.
func (u *UserUpsert) SetLang(v string) *UserUpsert {
	u.Set(user.FieldLang, v)
	return u
}

// UpdateLang sets the "lang" field to the value that was provided on create.
func (u *UserUpsert) UpdateLang() *UserUpsert {
	u.SetExcluded(user.FieldLang)
	return u
}

// SetAvatar sets the "avatar" field.
func (u *UserUpsert) SetAvatar(v string) *UserUpsert {
	u.Set(user.FieldAvatar, v)
	return u
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *UserUpsert) UpdateAvatar() *UserUpsert {
	u.SetExcluded(user.FieldAvatar)
	return u
}

// ClearAvatar clears the value of the "avatar" field.
func (u *UserUpsert) ClearAvatar() *UserUpsert {
	u.SetNull(user.FieldAvatar)
	return u
}

// SetCredit1 sets the "credit_1" field.
func (u *UserUpsert) SetCredit1(v float64) *UserUpsert {
	u.Set(user.FieldCredit1, v)
	return u
}

// UpdateCredit1 sets the "credit_1" field to the value that was provided on create.
func (u *UserUpsert) UpdateCredit1() *UserUpsert {
	u.SetExcluded(user.FieldCredit1)
	return u
}

// AddCredit1 adds v to the "credit_1" field.
func (u *UserUpsert) AddCredit1(v float64) *UserUpsert {
	u.Add(user.FieldCredit1, v)
	return u
}

// SetCredit2 sets the "credit_2" field.
func (u *UserUpsert) SetCredit2(v float64) *UserUpsert {
	u.Set(user.FieldCredit2, v)
	return u
}

// UpdateCredit2 sets the "credit_2" field to the value that was provided on create.
func (u *UserUpsert) UpdateCredit2() *UserUpsert {
	u.SetExcluded(user.FieldCredit2)
	return u
}

// AddCredit2 adds v to the "credit_2" field.
func (u *UserUpsert) AddCredit2(v float64) *UserUpsert {
	u.Add(user.FieldCredit2, v)
	return u
}

// SetCredit3 sets the "credit_3" field.
func (u *UserUpsert) SetCredit3(v float64) *UserUpsert {
	u.Set(user.FieldCredit3, v)
	return u
}

// UpdateCredit3 sets the "credit_3" field to the value that was provided on create.
func (u *UserUpsert) UpdateCredit3() *UserUpsert {
	u.SetExcluded(user.FieldCredit3)
	return u
}

// AddCredit3 adds v to the "credit_3" field.
func (u *UserUpsert) AddCredit3(v float64) *UserUpsert {
	u.Add(user.FieldCredit3, v)
	return u
}

// SetCredit4 sets the "credit_4" field.
func (u *UserUpsert) SetCredit4(v float64) *UserUpsert {
	u.Set(user.FieldCredit4, v)
	return u
}

// UpdateCredit4 sets the "credit_4" field to the value that was provided on create.
func (u *UserUpsert) UpdateCredit4() *UserUpsert {
	u.SetExcluded(user.FieldCredit4)
	return u
}

// AddCredit4 adds v to the "credit_4" field.
func (u *UserUpsert) AddCredit4(v float64) *UserUpsert {
	u.Add(user.FieldCredit4, v)
	return u
}

// SetCredit5 sets the "credit_5" field.
func (u *UserUpsert) SetCredit5(v float64) *UserUpsert {
	u.Set(user.FieldCredit5, v)
	return u
}

// UpdateCredit5 sets the "credit_5" field to the value that was provided on create.
func (u *UserUpsert) UpdateCredit5() *UserUpsert {
	u.SetExcluded(user.FieldCredit5)
	return u
}

// AddCredit5 adds v to the "credit_5" field.
func (u *UserUpsert) AddCredit5(v float64) *UserUpsert {
	u.Add(user.FieldCredit5, v)
	return u
}

// SetBankID sets the "bank_id" field.
func (u *UserUpsert) SetBankID(v uint64) *UserUpsert {
	u.Set(user.FieldBankID, v)
	return u
}

// UpdateBankID sets the "bank_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateBankID() *UserUpsert {
	u.SetExcluded(user.FieldBankID)
	return u
}

// ClearBankID clears the value of the "bank_id" field.
func (u *UserUpsert) ClearBankID() *UserUpsert {
	u.SetNull(user.FieldBankID)
	return u
}

// SetBankAccountName sets the "bank_account_name" field.
func (u *UserUpsert) SetBankAccountName(v string) *UserUpsert {
	u.Set(user.FieldBankAccountName, v)
	return u
}

// UpdateBankAccountName sets the "bank_account_name" field to the value that was provided on create.
func (u *UserUpsert) UpdateBankAccountName() *UserUpsert {
	u.SetExcluded(user.FieldBankAccountName)
	return u
}

// ClearBankAccountName clears the value of the "bank_account_name" field.
func (u *UserUpsert) ClearBankAccountName() *UserUpsert {
	u.SetNull(user.FieldBankAccountName)
	return u
}

// SetBankAccountNumber sets the "bank_account_number" field.
func (u *UserUpsert) SetBankAccountNumber(v string) *UserUpsert {
	u.Set(user.FieldBankAccountNumber, v)
	return u
}

// UpdateBankAccountNumber sets the "bank_account_number" field to the value that was provided on create.
func (u *UserUpsert) UpdateBankAccountNumber() *UserUpsert {
	u.SetExcluded(user.FieldBankAccountNumber)
	return u
}

// ClearBankAccountNumber clears the value of the "bank_account_number" field.
func (u *UserUpsert) ClearBankAccountNumber() *UserUpsert {
	u.SetNull(user.FieldBankAccountNumber)
	return u
}

// SetNationalID sets the "national_id" field.
func (u *UserUpsert) SetNationalID(v string) *UserUpsert {
	u.Set(user.FieldNationalID, v)
	return u
}

// UpdateNationalID sets the "national_id" field to the value that was provided on create.
func (u *UserUpsert) UpdateNationalID() *UserUpsert {
	u.SetExcluded(user.FieldNationalID)
	return u
}

// ClearNationalID clears the value of the "national_id" field.
func (u *UserUpsert) ClearNationalID() *UserUpsert {
	u.SetNull(user.FieldNationalID)
	return u
}

// SetFirstLogin sets the "first_login" field.
func (u *UserUpsert) SetFirstLogin(v bool) *UserUpsert {
	u.Set(user.FieldFirstLogin, v)
	return u
}

// UpdateFirstLogin sets the "first_login" field to the value that was provided on create.
func (u *UserUpsert) UpdateFirstLogin() *UserUpsert {
	u.SetExcluded(user.FieldFirstLogin)
	return u
}

// SetBanUntil sets the "ban_until" field.
func (u *UserUpsert) SetBanUntil(v time.Time) *UserUpsert {
	u.Set(user.FieldBanUntil, v)
	return u
}

// UpdateBanUntil sets the "ban_until" field to the value that was provided on create.
func (u *UserUpsert) UpdateBanUntil() *UserUpsert {
	u.SetExcluded(user.FieldBanUntil)
	return u
}

// ClearBanUntil clears the value of the "ban_until" field.
func (u *UserUpsert) ClearBanUntil() *UserUpsert {
	u.SetNull(user.FieldBanUntil)
	return u
}

// SetNewLoginAt sets the "new_login_at" field.
func (u *UserUpsert) SetNewLoginAt(v time.Time) *UserUpsert {
	u.Set(user.FieldNewLoginAt, v)
	return u
}

// UpdateNewLoginAt sets the "new_login_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateNewLoginAt() *UserUpsert {
	u.SetExcluded(user.FieldNewLoginAt)
	return u
}

// ClearNewLoginAt clears the value of the "new_login_at" field.
func (u *UserUpsert) ClearNewLoginAt() *UserUpsert {
	u.SetNull(user.FieldNewLoginAt)
	return u
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *UserUpsert) SetLastLoginAt(v time.Time) *UserUpsert {
	u.Set(user.FieldLastLoginAt, v)
	return u
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateLastLoginAt() *UserUpsert {
	u.SetExcluded(user.FieldLastLoginAt)
	return u
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *UserUpsert) ClearLastLoginAt() *UserUpsert {
	u.SetNull(user.FieldLastLoginAt)
	return u
}

// SetUnilevel sets the "unilevel" field.
func (u *UserUpsert) SetUnilevel(v uint64) *UserUpsert {
	u.Set(user.FieldUnilevel, v)
	return u
}

// UpdateUnilevel sets the "unilevel" field to the value that was provided on create.
func (u *UserUpsert) UpdateUnilevel() *UserUpsert {
	u.SetExcluded(user.FieldUnilevel)
	return u
}

// AddUnilevel adds v to the "unilevel" field.
func (u *UserUpsert) AddUnilevel(v uint64) *UserUpsert {
	u.Add(user.FieldUnilevel, v)
	return u
}

// ClearUnilevel clears the value of the "unilevel" field.
func (u *UserUpsert) ClearUnilevel() *UserUpsert {
	u.SetNull(user.FieldUnilevel)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *UserUpsert) SetCreatedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateCreatedAt() *UserUpsert {
	u.SetExcluded(user.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsert) SetUpdatedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateUpdatedAt() *UserUpsert {
	u.SetExcluded(user.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUpsert) SetDeletedAt(v time.Time) *UserUpsert {
	u.Set(user.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUpsert) UpdateDeletedAt() *UserUpsert {
	u.SetExcluded(user.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUpsert) ClearDeletedAt() *UserUpsert {
	u.SetNull(user.FieldDeletedAt)
	return u
}

// SetPassword3 sets the "password3" field.
func (u *UserUpsert) SetPassword3(v string) *UserUpsert {
	u.Set(user.FieldPassword3, v)
	return u
}

// UpdatePassword3 sets the "password3" field to the value that was provided on create.
func (u *UserUpsert) UpdatePassword3() *UserUpsert {
	u.SetExcluded(user.FieldPassword3)
	return u
}

// ClearPassword3 clears the value of the "password3" field.
func (u *UserUpsert) ClearPassword3() *UserUpsert {
	u.SetNull(user.FieldPassword3)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(user.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserUpsertOne) UpdateNewValues() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(user.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserUpsertOne) Ignore() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertOne) DoNothing() *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreate.OnConflict
// documentation for more info.
func (u *UserUpsertOne) Update(set func(*UserUpsert)) *UserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *UserUpsertOne) SetUsername(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUsername() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *UserUpsertOne) ClearUsername() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearUsername()
	})
}

// SetName sets the "name" field.
func (u *UserUpsertOne) SetName(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateName() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UserUpsertOne) ClearName() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearName()
	})
}

// SetEmail sets the "email" field.
func (u *UserUpsertOne) SetEmail(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateEmail() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *UserUpsertOne) ClearEmail() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearEmail()
	})
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (u *UserUpsertOne) SetEmailVerifiedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetEmailVerifiedAt(v)
	})
}

// UpdateEmailVerifiedAt sets the "email_verified_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateEmailVerifiedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateEmailVerifiedAt()
	})
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (u *UserUpsertOne) ClearEmailVerifiedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearEmailVerifiedAt()
	})
}

// SetPassword sets the "password" field.
func (u *UserUpsertOne) SetPassword(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePassword() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePassword()
	})
}

// SetPassword2 sets the "password2" field.
func (u *UserUpsertOne) SetPassword2(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPassword2(v)
	})
}

// UpdatePassword2 sets the "password2" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePassword2() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePassword2()
	})
}

// SetCountryID sets the "country_id" field.
func (u *UserUpsertOne) SetCountryID(v uint64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCountryID(v)
	})
}

// UpdateCountryID sets the "country_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCountryID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCountryID()
	})
}

// ClearCountryID clears the value of the "country_id" field.
func (u *UserUpsertOne) ClearCountryID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearCountryID()
	})
}

// SetContactCountryID sets the "contact_country_id" field.
func (u *UserUpsertOne) SetContactCountryID(v uint64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetContactCountryID(v)
	})
}

// UpdateContactCountryID sets the "contact_country_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateContactCountryID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateContactCountryID()
	})
}

// ClearContactCountryID clears the value of the "contact_country_id" field.
func (u *UserUpsertOne) ClearContactCountryID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearContactCountryID()
	})
}

// SetContactNumber sets the "contact_number" field.
func (u *UserUpsertOne) SetContactNumber(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetContactNumber(v)
	})
}

// UpdateContactNumber sets the "contact_number" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateContactNumber() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateContactNumber()
	})
}

// ClearContactNumber clears the value of the "contact_number" field.
func (u *UserUpsertOne) ClearContactNumber() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearContactNumber()
	})
}

// SetFullContactNumber sets the "full_contact_number" field.
func (u *UserUpsertOne) SetFullContactNumber(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetFullContactNumber(v)
	})
}

// UpdateFullContactNumber sets the "full_contact_number" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateFullContactNumber() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateFullContactNumber()
	})
}

// ClearFullContactNumber clears the value of the "full_contact_number" field.
func (u *UserUpsertOne) ClearFullContactNumber() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearFullContactNumber()
	})
}

// SetIntroducerUserID sets the "introducer_user_id" field.
func (u *UserUpsertOne) SetIntroducerUserID(v uint64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetIntroducerUserID(v)
	})
}

// UpdateIntroducerUserID sets the "introducer_user_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateIntroducerUserID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateIntroducerUserID()
	})
}

// ClearIntroducerUserID clears the value of the "introducer_user_id" field.
func (u *UserUpsertOne) ClearIntroducerUserID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearIntroducerUserID()
	})
}

// SetLang sets the "lang" field.
func (u *UserUpsertOne) SetLang(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetLang(v)
	})
}

// UpdateLang sets the "lang" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateLang() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLang()
	})
}

// SetAvatar sets the "avatar" field.
func (u *UserUpsertOne) SetAvatar(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetAvatar(v)
	})
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateAvatar() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAvatar()
	})
}

// ClearAvatar clears the value of the "avatar" field.
func (u *UserUpsertOne) ClearAvatar() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearAvatar()
	})
}

// SetCredit1 sets the "credit_1" field.
func (u *UserUpsertOne) SetCredit1(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit1(v)
	})
}

// AddCredit1 adds v to the "credit_1" field.
func (u *UserUpsertOne) AddCredit1(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit1(v)
	})
}

// UpdateCredit1 sets the "credit_1" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCredit1() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit1()
	})
}

// SetCredit2 sets the "credit_2" field.
func (u *UserUpsertOne) SetCredit2(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit2(v)
	})
}

// AddCredit2 adds v to the "credit_2" field.
func (u *UserUpsertOne) AddCredit2(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit2(v)
	})
}

// UpdateCredit2 sets the "credit_2" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCredit2() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit2()
	})
}

// SetCredit3 sets the "credit_3" field.
func (u *UserUpsertOne) SetCredit3(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit3(v)
	})
}

// AddCredit3 adds v to the "credit_3" field.
func (u *UserUpsertOne) AddCredit3(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit3(v)
	})
}

// UpdateCredit3 sets the "credit_3" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCredit3() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit3()
	})
}

// SetCredit4 sets the "credit_4" field.
func (u *UserUpsertOne) SetCredit4(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit4(v)
	})
}

// AddCredit4 adds v to the "credit_4" field.
func (u *UserUpsertOne) AddCredit4(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit4(v)
	})
}

// UpdateCredit4 sets the "credit_4" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCredit4() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit4()
	})
}

// SetCredit5 sets the "credit_5" field.
func (u *UserUpsertOne) SetCredit5(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit5(v)
	})
}

// AddCredit5 adds v to the "credit_5" field.
func (u *UserUpsertOne) AddCredit5(v float64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit5(v)
	})
}

// UpdateCredit5 sets the "credit_5" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCredit5() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit5()
	})
}

// SetBankID sets the "bank_id" field.
func (u *UserUpsertOne) SetBankID(v uint64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetBankID(v)
	})
}

// UpdateBankID sets the "bank_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateBankID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBankID()
	})
}

// ClearBankID clears the value of the "bank_id" field.
func (u *UserUpsertOne) ClearBankID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearBankID()
	})
}

// SetBankAccountName sets the "bank_account_name" field.
func (u *UserUpsertOne) SetBankAccountName(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetBankAccountName(v)
	})
}

// UpdateBankAccountName sets the "bank_account_name" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateBankAccountName() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBankAccountName()
	})
}

// ClearBankAccountName clears the value of the "bank_account_name" field.
func (u *UserUpsertOne) ClearBankAccountName() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearBankAccountName()
	})
}

// SetBankAccountNumber sets the "bank_account_number" field.
func (u *UserUpsertOne) SetBankAccountNumber(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetBankAccountNumber(v)
	})
}

// UpdateBankAccountNumber sets the "bank_account_number" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateBankAccountNumber() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBankAccountNumber()
	})
}

// ClearBankAccountNumber clears the value of the "bank_account_number" field.
func (u *UserUpsertOne) ClearBankAccountNumber() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearBankAccountNumber()
	})
}

// SetNationalID sets the "national_id" field.
func (u *UserUpsertOne) SetNationalID(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetNationalID(v)
	})
}

// UpdateNationalID sets the "national_id" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateNationalID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNationalID()
	})
}

// ClearNationalID clears the value of the "national_id" field.
func (u *UserUpsertOne) ClearNationalID() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearNationalID()
	})
}

// SetFirstLogin sets the "first_login" field.
func (u *UserUpsertOne) SetFirstLogin(v bool) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetFirstLogin(v)
	})
}

// UpdateFirstLogin sets the "first_login" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateFirstLogin() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateFirstLogin()
	})
}

// SetBanUntil sets the "ban_until" field.
func (u *UserUpsertOne) SetBanUntil(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetBanUntil(v)
	})
}

// UpdateBanUntil sets the "ban_until" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateBanUntil() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBanUntil()
	})
}

// ClearBanUntil clears the value of the "ban_until" field.
func (u *UserUpsertOne) ClearBanUntil() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearBanUntil()
	})
}

// SetNewLoginAt sets the "new_login_at" field.
func (u *UserUpsertOne) SetNewLoginAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetNewLoginAt(v)
	})
}

// UpdateNewLoginAt sets the "new_login_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateNewLoginAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNewLoginAt()
	})
}

// ClearNewLoginAt clears the value of the "new_login_at" field.
func (u *UserUpsertOne) ClearNewLoginAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearNewLoginAt()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *UserUpsertOne) SetLastLoginAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateLastLoginAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *UserUpsertOne) ClearLastLoginAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearLastLoginAt()
	})
}

// SetUnilevel sets the "unilevel" field.
func (u *UserUpsertOne) SetUnilevel(v uint64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUnilevel(v)
	})
}

// AddUnilevel adds v to the "unilevel" field.
func (u *UserUpsertOne) AddUnilevel(v uint64) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.AddUnilevel(v)
	})
}

// UpdateUnilevel sets the "unilevel" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUnilevel() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUnilevel()
	})
}

// ClearUnilevel clears the value of the "unilevel" field.
func (u *UserUpsertOne) ClearUnilevel() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearUnilevel()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserUpsertOne) SetCreatedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateCreatedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsertOne) SetUpdatedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateUpdatedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUpsertOne) SetDeletedAt(v time.Time) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUpsertOne) UpdateDeletedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUpsertOne) ClearDeletedAt() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPassword3 sets the "password3" field.
func (u *UserUpsertOne) SetPassword3(v string) *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.SetPassword3(v)
	})
}

// UpdatePassword3 sets the "password3" field to the value that was provided on create.
func (u *UserUpsertOne) UpdatePassword3() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePassword3()
	})
}

// ClearPassword3 clears the value of the "password3" field.
func (u *UserUpsertOne) ClearPassword3() *UserUpsertOne {
	return u.Update(func(s *UserUpsert) {
		s.ClearPassword3()
	})
}

// Exec executes the query.
func (u *UserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserUpsertOne) ID(ctx context.Context) (id uint64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserUpsertOne) IDX(ctx context.Context) uint64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
	conflict []sql.ConflictOption
}

// Save creates the User entities in the database.
func (ucb *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*User, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ucb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.User.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetUsername(v+v).
//		}).
//		Exec(ctx)
func (ucb *UserCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserUpsertBulk {
	ucb.conflict = opts
	return &UserUpsertBulk{
		create: ucb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ucb *UserCreateBulk) OnConflictColumns(columns ...string) *UserUpsertBulk {
	ucb.conflict = append(ucb.conflict, sql.ConflictColumns(columns...))
	return &UserUpsertBulk{
		create: ucb,
	}
}

// UserUpsertBulk is the builder for "upsert"-ing
// a bulk of User nodes.
type UserUpsertBulk struct {
	create *UserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(user.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *UserUpsertBulk) UpdateNewValues() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(user.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.User.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserUpsertBulk) Ignore() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserUpsertBulk) DoNothing() *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserCreateBulk.OnConflict
// documentation for more info.
func (u *UserUpsertBulk) Update(set func(*UserUpsert)) *UserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUsername sets the "username" field.
func (u *UserUpsertBulk) SetUsername(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUsername(v)
	})
}

// UpdateUsername sets the "username" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUsername() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUsername()
	})
}

// ClearUsername clears the value of the "username" field.
func (u *UserUpsertBulk) ClearUsername() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearUsername()
	})
}

// SetName sets the "name" field.
func (u *UserUpsertBulk) SetName(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateName() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateName()
	})
}

// ClearName clears the value of the "name" field.
func (u *UserUpsertBulk) ClearName() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearName()
	})
}

// SetEmail sets the "email" field.
func (u *UserUpsertBulk) SetEmail(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateEmail() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateEmail()
	})
}

// ClearEmail clears the value of the "email" field.
func (u *UserUpsertBulk) ClearEmail() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearEmail()
	})
}

// SetEmailVerifiedAt sets the "email_verified_at" field.
func (u *UserUpsertBulk) SetEmailVerifiedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetEmailVerifiedAt(v)
	})
}

// UpdateEmailVerifiedAt sets the "email_verified_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateEmailVerifiedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateEmailVerifiedAt()
	})
}

// ClearEmailVerifiedAt clears the value of the "email_verified_at" field.
func (u *UserUpsertBulk) ClearEmailVerifiedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearEmailVerifiedAt()
	})
}

// SetPassword sets the "password" field.
func (u *UserUpsertBulk) SetPassword(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePassword() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePassword()
	})
}

// SetPassword2 sets the "password2" field.
func (u *UserUpsertBulk) SetPassword2(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPassword2(v)
	})
}

// UpdatePassword2 sets the "password2" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePassword2() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePassword2()
	})
}

// SetCountryID sets the "country_id" field.
func (u *UserUpsertBulk) SetCountryID(v uint64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCountryID(v)
	})
}

// UpdateCountryID sets the "country_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCountryID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCountryID()
	})
}

// ClearCountryID clears the value of the "country_id" field.
func (u *UserUpsertBulk) ClearCountryID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearCountryID()
	})
}

// SetContactCountryID sets the "contact_country_id" field.
func (u *UserUpsertBulk) SetContactCountryID(v uint64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetContactCountryID(v)
	})
}

// UpdateContactCountryID sets the "contact_country_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateContactCountryID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateContactCountryID()
	})
}

// ClearContactCountryID clears the value of the "contact_country_id" field.
func (u *UserUpsertBulk) ClearContactCountryID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearContactCountryID()
	})
}

// SetContactNumber sets the "contact_number" field.
func (u *UserUpsertBulk) SetContactNumber(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetContactNumber(v)
	})
}

// UpdateContactNumber sets the "contact_number" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateContactNumber() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateContactNumber()
	})
}

// ClearContactNumber clears the value of the "contact_number" field.
func (u *UserUpsertBulk) ClearContactNumber() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearContactNumber()
	})
}

// SetFullContactNumber sets the "full_contact_number" field.
func (u *UserUpsertBulk) SetFullContactNumber(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetFullContactNumber(v)
	})
}

// UpdateFullContactNumber sets the "full_contact_number" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateFullContactNumber() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateFullContactNumber()
	})
}

// ClearFullContactNumber clears the value of the "full_contact_number" field.
func (u *UserUpsertBulk) ClearFullContactNumber() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearFullContactNumber()
	})
}

// SetIntroducerUserID sets the "introducer_user_id" field.
func (u *UserUpsertBulk) SetIntroducerUserID(v uint64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetIntroducerUserID(v)
	})
}

// UpdateIntroducerUserID sets the "introducer_user_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateIntroducerUserID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateIntroducerUserID()
	})
}

// ClearIntroducerUserID clears the value of the "introducer_user_id" field.
func (u *UserUpsertBulk) ClearIntroducerUserID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearIntroducerUserID()
	})
}

// SetLang sets the "lang" field.
func (u *UserUpsertBulk) SetLang(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetLang(v)
	})
}

// UpdateLang sets the "lang" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateLang() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLang()
	})
}

// SetAvatar sets the "avatar" field.
func (u *UserUpsertBulk) SetAvatar(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetAvatar(v)
	})
}

// UpdateAvatar sets the "avatar" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateAvatar() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateAvatar()
	})
}

// ClearAvatar clears the value of the "avatar" field.
func (u *UserUpsertBulk) ClearAvatar() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearAvatar()
	})
}

// SetCredit1 sets the "credit_1" field.
func (u *UserUpsertBulk) SetCredit1(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit1(v)
	})
}

// AddCredit1 adds v to the "credit_1" field.
func (u *UserUpsertBulk) AddCredit1(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit1(v)
	})
}

// UpdateCredit1 sets the "credit_1" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCredit1() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit1()
	})
}

// SetCredit2 sets the "credit_2" field.
func (u *UserUpsertBulk) SetCredit2(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit2(v)
	})
}

// AddCredit2 adds v to the "credit_2" field.
func (u *UserUpsertBulk) AddCredit2(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit2(v)
	})
}

// UpdateCredit2 sets the "credit_2" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCredit2() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit2()
	})
}

// SetCredit3 sets the "credit_3" field.
func (u *UserUpsertBulk) SetCredit3(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit3(v)
	})
}

// AddCredit3 adds v to the "credit_3" field.
func (u *UserUpsertBulk) AddCredit3(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit3(v)
	})
}

// UpdateCredit3 sets the "credit_3" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCredit3() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit3()
	})
}

// SetCredit4 sets the "credit_4" field.
func (u *UserUpsertBulk) SetCredit4(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit4(v)
	})
}

// AddCredit4 adds v to the "credit_4" field.
func (u *UserUpsertBulk) AddCredit4(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit4(v)
	})
}

// UpdateCredit4 sets the "credit_4" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCredit4() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit4()
	})
}

// SetCredit5 sets the "credit_5" field.
func (u *UserUpsertBulk) SetCredit5(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCredit5(v)
	})
}

// AddCredit5 adds v to the "credit_5" field.
func (u *UserUpsertBulk) AddCredit5(v float64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddCredit5(v)
	})
}

// UpdateCredit5 sets the "credit_5" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCredit5() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCredit5()
	})
}

// SetBankID sets the "bank_id" field.
func (u *UserUpsertBulk) SetBankID(v uint64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetBankID(v)
	})
}

// UpdateBankID sets the "bank_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateBankID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBankID()
	})
}

// ClearBankID clears the value of the "bank_id" field.
func (u *UserUpsertBulk) ClearBankID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearBankID()
	})
}

// SetBankAccountName sets the "bank_account_name" field.
func (u *UserUpsertBulk) SetBankAccountName(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetBankAccountName(v)
	})
}

// UpdateBankAccountName sets the "bank_account_name" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateBankAccountName() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBankAccountName()
	})
}

// ClearBankAccountName clears the value of the "bank_account_name" field.
func (u *UserUpsertBulk) ClearBankAccountName() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearBankAccountName()
	})
}

// SetBankAccountNumber sets the "bank_account_number" field.
func (u *UserUpsertBulk) SetBankAccountNumber(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetBankAccountNumber(v)
	})
}

// UpdateBankAccountNumber sets the "bank_account_number" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateBankAccountNumber() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBankAccountNumber()
	})
}

// ClearBankAccountNumber clears the value of the "bank_account_number" field.
func (u *UserUpsertBulk) ClearBankAccountNumber() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearBankAccountNumber()
	})
}

// SetNationalID sets the "national_id" field.
func (u *UserUpsertBulk) SetNationalID(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetNationalID(v)
	})
}

// UpdateNationalID sets the "national_id" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateNationalID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNationalID()
	})
}

// ClearNationalID clears the value of the "national_id" field.
func (u *UserUpsertBulk) ClearNationalID() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearNationalID()
	})
}

// SetFirstLogin sets the "first_login" field.
func (u *UserUpsertBulk) SetFirstLogin(v bool) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetFirstLogin(v)
	})
}

// UpdateFirstLogin sets the "first_login" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateFirstLogin() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateFirstLogin()
	})
}

// SetBanUntil sets the "ban_until" field.
func (u *UserUpsertBulk) SetBanUntil(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetBanUntil(v)
	})
}

// UpdateBanUntil sets the "ban_until" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateBanUntil() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateBanUntil()
	})
}

// ClearBanUntil clears the value of the "ban_until" field.
func (u *UserUpsertBulk) ClearBanUntil() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearBanUntil()
	})
}

// SetNewLoginAt sets the "new_login_at" field.
func (u *UserUpsertBulk) SetNewLoginAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetNewLoginAt(v)
	})
}

// UpdateNewLoginAt sets the "new_login_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateNewLoginAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateNewLoginAt()
	})
}

// ClearNewLoginAt clears the value of the "new_login_at" field.
func (u *UserUpsertBulk) ClearNewLoginAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearNewLoginAt()
	})
}

// SetLastLoginAt sets the "last_login_at" field.
func (u *UserUpsertBulk) SetLastLoginAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetLastLoginAt(v)
	})
}

// UpdateLastLoginAt sets the "last_login_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateLastLoginAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateLastLoginAt()
	})
}

// ClearLastLoginAt clears the value of the "last_login_at" field.
func (u *UserUpsertBulk) ClearLastLoginAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearLastLoginAt()
	})
}

// SetUnilevel sets the "unilevel" field.
func (u *UserUpsertBulk) SetUnilevel(v uint64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUnilevel(v)
	})
}

// AddUnilevel adds v to the "unilevel" field.
func (u *UserUpsertBulk) AddUnilevel(v uint64) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.AddUnilevel(v)
	})
}

// UpdateUnilevel sets the "unilevel" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUnilevel() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUnilevel()
	})
}

// ClearUnilevel clears the value of the "unilevel" field.
func (u *UserUpsertBulk) ClearUnilevel() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearUnilevel()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *UserUpsertBulk) SetCreatedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateCreatedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UserUpsertBulk) SetUpdatedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateUpdatedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *UserUpsertBulk) SetDeletedAt(v time.Time) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdateDeletedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *UserUpsertBulk) ClearDeletedAt() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPassword3 sets the "password3" field.
func (u *UserUpsertBulk) SetPassword3(v string) *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.SetPassword3(v)
	})
}

// UpdatePassword3 sets the "password3" field to the value that was provided on create.
func (u *UserUpsertBulk) UpdatePassword3() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.UpdatePassword3()
	})
}

// ClearPassword3 clears the value of the "password3" field.
func (u *UserUpsertBulk) ClearPassword3() *UserUpsertBulk {
	return u.Update(func(s *UserUpsert) {
		s.ClearPassword3()
	})
}

// Exec executes the query.
func (u *UserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
